var express = require('express');
var router = express.Router();


router.get('/', function(req, res, next) {
  res.render('Home/index',
   { 
     profile: '/images/profile.png',
     profileline1: 'I am Anu Bala',
     profileline2: 'Full Stack Web Developer',
     mailid : 'mailto:anubala331@gmail.com',
     email: 'anubala331.com',
     location: 'Ontario, Canada',
     gitlink: 'https://github.com/anubala331',
     linkdinlink: 'https://www.linkedin.com/in/anu-bala-8b4a72bb/',
     instalink: 'https://www.instagram.com/anu.kamboj.509/',
     facebooklink: 'https://www.facebook.com/anu.kamboj.509',
     twitterlink: 'https://twitter.com/AnuBala22357503',
     bloglink: 'https://www.emblogic.com/forum/discussions/p22',
     objective: 'To seeking an opportunity which can help me build my development skills\
     in the application layer. I am looking for challenging position in reputable company\
     in which I am able to perform the job with knowledge and experience that I have.',
     banner: 'images/banner/banner.jpg',
     introimg: 'images/banner/intro.jpg',
     introline1: 'Let me introduce skills',
     intropoint1: 'Programming Languages',
     languages: 'C/C++, Html, JavaScript, Ajax, CSS, Nodejs, Angular, Express, XML, C Sharp, Swift',
     intropoint2: 'IDE',
     editors: 'NetBeans, eclipse.',
     services: 'Networking Services',
     servicenames:'SSH, SCP, FTP, Microhttpd, Web Sockets',
     versiontools: 'Version Tools',
     toolnames: 'GIT, SVN',
     deploymenttools: 'Development tools',
     depnames: 'NGINX, MONIT, PG_ACTIVITY, GATEWAY',
     downloadCV: 'Download cv',
     titlepro: 'PROJECTS',
     currentPro: 'Current working Project',
     currentPos: 'Lead Engineer',
     pro11: 'Completed 4G trainings and Undergone 5G trainings since 1st of September,2020.',
     pro12: 'Got 5G Certification of completion from Award Solutions.',
     pro13: 'After thorough lectures of approximately 2 months and attempting exam with threshold or eligibility marking of 75%.',
     pro14: 'Good understanding of 5G NR, ORAN, MANO, EDGE COMPUTING ORCHESTRATION.',
     pro1date: 'Feb 2021 - present',
     pro2name: 'Trinetra',
     pro2pos: 'Lead Engineer',
     pro21: 'To speed up working efficiency while shooting by different sony model cameras using different types of A-mount and E-mount lenses.',
     pro22: 'To bring its high-speed communication with imaging edge mobile app and PC Remote App is the main target.',
     pro23: 'Camera has multiple Tabs, which contains multiple groups and groups has pages.',
     pro24: 'Pages contain many menu items which provide us camera functionalities.',
     pro25: 'Root node is made for all Tabs, pages, menu items and every one of these have their individual node themselves. ',
     pro26: 'Root nodes, Tab icons, menu name, group name and other widgets which are made using epseed conductor tool or common shooting manager are placed on layouts. ',
     pro27: 'Layouts combine to form a state and multiple states combine to form a view using state chart editor tool. ',
     pro28: 'State transition takes place in view. Guards(conditions) are applied to open and close views.',
     pro2time: '2018 - 2019',
     pro3name: 'NGUCC Contaque Dialer',
     pro3pos: 'Senior Software Development',
     pro31: 'One of the biggest challenges in Hi-tech industry is customer retention.',
     pro32: 'This is modern cloud based multilingual next generation unified call center solution for outbound and inbound calls. ',
     pro33: 'It will power up inbound and outbound customer interaction. ',
     pro34: 'It is helpful to control agents remotely by tracking.',
     pro35: 'It improves agent handle time. High agent productivity through better connect ratio. ',
     pro36: 'This is the major project ever I have worked on. Different versions of NGUCC product are released.',
     pro37: 'Domain name will be provided to access the software. High agent availability through, asterisk configurations, dialer with different dial methods, call types and rules are used.',
     pro38: 'Preview, power, ratio, agent wise and Algo are different dial methods which are used for better connect ratio with customers of call center.',
     pro39: 'Callback, campaign call routing, alternate dialing solutions are also provided. Dialing to customers of call center by different rules in gap of different timings is also provided in Lead Recycle rule.',
     pro40: 'I have worked on some of them (2.2,2.3,3.0,3.1,4.1,4.2,4.3,5.0).',
     pro3time: '2015 - 2018',
     ticketingimg: 'images/Projects/ngucc.jpg',
     pro4name: 'Ticketing System',
     pro4title: 'Senior Software Development',
     pro41: 'Ticketing system is used by management team to generate new tickets based on internal and external issues of organization.',
     pro42: 'It takes incoming customer request for support and automatically generates a customer service ticket via email/phone call.',
     pro43: 'This application can be committed to NGUCC (Unified Call Center Solution) to generate tickets by agent during attending calls of clients. ',
     pro44: 'Team of big organization can be handled very easily, smoothly.',
     pro45: 'New tickets can be escalated to the specified teams and assigned to particular user in particular hierarchy. ',
     pro46: 'Previous tickets can also be searched and modified.',
     pro47: 'Email server is also configured to auto mode ticket generation by sending mail by client to email id provided to client and given response of ticket generation back to client of organization.',
     pro4time: '2018',
     pro5name: 'Oliva Crm',
     pro5pos: 'Senior Software Development',
     pro5image: 'images/Projects/oliva.jpg',
     pro51: 'Oliva CRM is a Medical Practice Management Software that deals with the day-to-day operations of a medical practice.',
     pro52: 'Oliva Crm allows users to capture patient demographics through multiple clinics in multiple locations, schedule appointments and generate reports.',
     pro53: 'This Application can commit to Unified Call Center Product to generate patient information by agents during attending calls of patients.',
     pro54: 'Due to this, all the information of patients can be maintained very easily and smoothly, quality service can be provided to patients.',
     pro55: 'Electronic medical records enable doctors to view patient summaries, create comprehensive case notes, prescribe correct medications and order investigations. ',
     pro56: 'It enhances the operational efficiency of dispensaries, clinics and even hospitals. Reports are displayed to view patient records and agent performance. ',
     pro57: 'Data can be analyzed to identify and test the most effective means for engaging different types of patients.',
     pro5time: '2018',
     pro6image: 'images/Projects/onlinetesting.jpg',
     pro6name: 'Online Testing System',
     pro6pos: 'Senior Software Development',
     pro61: 'This is web application for online exams. ',
     pro62: 'Web based exams provide instructors and teachers with a flexible distribution channel that allows students to take tests wherever they may be.',
     pro63: 'With features such as time limits, instant feedback, add media to questions, accurate grading and many more settings.',
     pro64: 'There is no need to worry about downloads, software requirements or regular maintenance.',
     pro6time: '2018',
     orgtitle: 'ORGANIZATIONS',
     embimage: 'images/Organizations/emblogic.png',
     embname: 'Emblogic Embedded Technologies Private Limited',
     avisimage: 'images/Organizations/avissol.png',
     avisname: 'Avissol Solutions Private Limited',
     avistime: 'August 2015 - July 2018',
     hclimage: 'images/Organizations/HCL.png',
     hclname: 'HCL Technologies Private Limited',
     hcltime: 'August 2018 - Present',
     footerimg: 'images/footer.PNG',
     contactno:'Contact Me : +91 9953225867.',
     name: 'Full Name',
     emailplace: 'Your Email Address',
     messageplace: 'Your Message',
     send : 'Send'
  });
});

router.get('/About', (req,res,next) => {
  res.render('About/index', {
   topline: 'A Full Stack Web Application Developer with 6+ years of experience in C/C++ and designing and development user interfaces. ', 
   point1: 'Understanding of MVC Architecture and DesignPatterns.',
   point2: 'Proficient with Datastructures and algorithms.',
   point3: 'Worked in SCRUM Agile development environment.',
   point4: 'Worked on Window Platform Foundation(WPF) using C#.',
   point5: 'Worked on NodeJS, Angular JS & Express.',
   point6: 'Certified in 4G/5G Telecom Technologies.',
   point7: 'Worked on Microhttpd, & Web Sockets.',
   point8: 'Expertise with database PostgreSQL & libzdb.',
   point9: 'Experienced in  C/C++ with multithreading and UI Designing.',
   point10: 'Hands on experience to send and receive SMS using gateway api’s.',
   point11: 'Expertise in sending and receiving mails using vmime.',
   point12: 'Hands on experience in web UI languages like html5, CSS, js, ajax, xml & gdb tool.',
   point13: 'Expertise to handle services to execute services in auto mode using Monit.',
   point14: 'Expertise in modern cloud based multilingual next generation unified call center solution.',
   point15: 'Good Understanding of Creating New Process & Replacing the created processes using fork and excel.',
   point16: 'Expert in Communicating Processes using Linux Programming: IPC Mechanisms like Pipes, FIFOs, Message Queues and Shared Memory.',
   point17: 'Professed in Network Programming including Socket programming with ftp using POSIX Threads and communicated number of systems.',
   point18: 'Basic understanding of Character, Serial & Parallel Port Device Drivers with toolchain(certification).',
   point19: 'Proficient in using development tools like make, Make file.',
   point20: 'Basic knowledge of swift, shell scripting & python.',
   gitlink: 'https://github.com/anubala331',
   linkdinlink: 'https://www.linkedin.com/in/anu-bala-8b4a72bb/',
   instalink: 'https://www.instagram.com/anu.kamboj.509/',
   facebooklink: 'https://www.facebook.com/anu.kamboj.509',
   twitterlink: 'https://twitter.com/AnuBala22357503',
   bloglink: 'https://www.emblogic.com/forum/discussions/p22',
   mailid : 'mailto:anubala331@gmail.com'
  });
});

// router.get('/Projects', (req, res, next)=> {
//   res.render('Projects/index', {title: 'My Projects'})
// })

// router.get('/Contact', (req, res, next)=> {
//   res.render('Contact/index', {title: 'My Contact'})
// })


module.exports = router;
